### ISSUE TITLE
hi, can work use your work to generate a synthetic dataset to train some ML models on and of course give credits to you in my work. thanks 

### ISSUE THREAD

**Issue by AhmedDiaaeldin** [NikolayKozlovskiy/GPS_GENERATOR#1]
can work use your work to generate a synthetic dataset to train some ML models on and of course give credits to you in my work. thanks

**Comment by NikolayKozlovskiy** [comment]
Hello, 

Thanks for writing me. I have added Apache License 2.0 in the repo. You can freely use the code, please let me know if something is not working or could be improved. I would personally be interested if you decide to use GPS Generator with different config params, have not played with them a lot. 

Best, 
Nikolay

**Comment by AhmedDiaaeldin** [comment]
All respect to you really,
your work may be a saver to me in my graduation project. 
thanks a lot, and of course I will send you updates God willing.
